services:
  php:
    build: .
    container_name: php_chat
    ports: 
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db: 
    image: mysql:8
    container_name: db_chat
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat_db
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"

volumes:
  db-data: